<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0
             http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dk.ek.dat</groupId>
    <artifactId>mit-spil</artifactId>
    <version>1.0.0</version>

    <properties>
        <maven.compiler.source>21</maven.compiler.source>
        <maven.compiler.target>21</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <!-- Her henter Maven spil-biblioteket. -->
    <repositories>
        <repository>
            <id>tobiasgrundtvig</id>
            <url>https://maven.tobiasgrundtvig.dk</url>
        </repository>
    </repositories>

    <dependencies>
        <dependency>
            <groupId>textgame</groupId>
            <artifactId>textgame-client</artifactId>
            <version>0.2.0</version>
        </dependency>
    </dependencies>
</project>
